### ISSUE TITLE
A reproducible invalid connection error occurs when performing transaction processing within an HTTP request.

### ISSUE THREAD

**Issue by natsumesou** [tidbcloud/serverless-js#61]
When using `Promise.all` inside a transaction to asynchronously execute multiple `tx.execute` operations.

```js
const tx = await conn.begin();
await Promise.all([
    tx.execute("select * from test"),
    tx.execute("select * from test")
]);
await tx.commit();
```

An error occurs when reloading the page during this request:

```
file:///Users/n/Development/indivisual/test/node_modules/@tidbcloud/serverless/dist/index.js:237
      error = new DatabaseError(e.message, response.status, e);
              ^

DatabaseError: Rollback transaction fail: invalid connection
    at postQuery (file:///Users/n/Development/indivisual/test/node_modules/@tidbcloud/serverless/dist/index.js:237:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _Connection.execute (file:///Users/n/Development/indivisual/test/node_modules/@tidbcloud/serverless/dist/index.js:314:18)
    at async Server.<anonymous> (file:///Users/n/Development/indivisual/test/index.js:15:5) {
  status: 500,
  details: {
    code: 151100004,
    message: 'Rollback transaction fail: invalid connection'
  }
}
```

This error does not occur when all queries are executed synchronously without using `Promise.all`.

```js
const tx = await conn.begin();
await tx.execute("select * from test");
await tx.execute("select * from test");
await tx.commit();
```

Is there a way to address this error?

I have prepared a minimal code example repository for reproduction, and here are the steps:
https://github.com/natsumesou/minimal-reproduction-for-tidb-serverless-transaction-error

1. `git clone https://github.com/natsumesou/minimal-reproduction-for-tidb-serverless-transaction-error.git`
2. `cd minimal-reproduction-for-tidb-serverless-transaction-error`
3. `mysql -h <host> -P 4000 -u <user> -p <database> < seed.sql`
4. `DB_CONNECTING_URL="mysql://<connection_string>" node index.js`
5. open http://localhost:4000
6. Quickly reload the page several times

### versions

- Node.js 20.10.0
- tidbcloud/serverless 0.1.1

**Comment by shiyuhang0** [comment]
Thank you for your report. 
The issue is under investigation and we will comment here once we find the reason

**Comment by shiyuhang0** [comment]
Hi, We have found the root cause of the issue. The conclusion is that serverless-js does not support executing transaction concurrency.

## why

When a transaction is active on TiDB Serverless, every operation on the transaction will go through the same connection. Similar to the MySQL connection model, TiDB Serverless does not support multiple SQLs run in parallel on the same connection. [This article](https://proxysql.com/documentation/multiplexing/) is a good reference.

## What will we do

The serverless driver will do nothing about it, just like most of the MySQL driver. For example, the go-sql-driver, here is the [issue](https://github.com/go-sql-driver/mysql/issues/792). The only thing we will do is document it https://github.com/tidbcloud/serverless-js/pull/62.

## Suggestion

According to the description above, Here is the suggestion for you:
- Run the transaction serially
- Don't use transaction

**Comment by natsumesou** [comment]
@shiyuhang0 Thank you for your response.
I will process this sequentially.
Also, updating the documentation would be helpful.
Thank you very much.
